language: ruby
env:
  matrix:
  - RACK_ENV=development
  global:
    secure: VcHomtnyOeiaR7ew2j4rInHg9Qw76avFJT5SkiHZXxAtBgL+dumRcw1fQOSmtNPDQAXXcWhckZqkEFAAZ//NkLkz/3ejg/qMEktTCv8QyIqD6ESmx5mqZdIWdD/owsHqMPo3zctAJbmR4Kq9pYyTYu0N+BL7hPCRqucBcAy5S44=
rvm:
- 2.0.0
git:
  depth: 100
addons:
  code_climate:
    repo_token: 8548eba8b9cf270d3deee106d407bb9a9fdc3a44df9b2e03d1a68b0e6200117c
before_install:
- openssl aes-256-cbc -K $encrypted_fb0045c28a64_key -iv $encrypted_fb0045c28a64_iv
  -in escualo_rsa.enc -out escualo_rsa -d
after_success:
- wget https://raw.githubusercontent.com/mumuki/mumuki-escualo-deploy/master/travis_deploy && chmod u+x travis_deploy
- ./travis_deploy gobstones
